# Generated by Django 3.1.13 on 2022-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('store', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
