# Generated by Django 3.1.13 on 2022-10-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordsProds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
                ('ref_prods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.prods', verbose_name='Ref Prods')),
            ],
        ),
    ]
